services:
  dh_doctrine_audit.user_provider:
    class: DH\DoctrineAuditBundle\User\TokenStorageUserProvider
    arguments: ["@security.helper"]
    public: true

  dh_doctrine_audit.configuration:
    class: DH\DoctrineAuditBundle\AuditConfiguration
    arguments: ["%dh_doctrine_audit.configuration%", "@dh_doctrine_audit.user_provider", "@request_stack"]
    public: true

  DH\DoctrineAuditBundle\AuditConfiguration:
    alias: dh_doctrine_audit.configuration
    public: true

  dh_doctrine_audit.reader:
    class: DH\DoctrineAuditBundle\AuditReader
    arguments: ["@dh_doctrine_audit.configuration", "@doctrine.orm.default_entity_manager"]
    public: true

  DH\DoctrineAuditBundle\AuditReader:
    alias: dh_doctrine_audit.reader
    public: true

  dh_doctrine_audit.event_subscriber.audit:
    class: DH\DoctrineAuditBundle\EventSubscriber\AuditSubscriber
    arguments: ["@dh_doctrine_audit.configuration"]
    tags:
      - { name: doctrine.event_subscriber, connection: default }

  dh_doctrine_audit.event_subscriber.create_schema:
    class: DH\DoctrineAuditBundle\EventSubscriber\CreateSchemaListener
    arguments: ["@dh_doctrine_audit.configuration"]
    tags:
      - { name: doctrine.event_subscriber, connection: default }

  dh_doctrine_audit.twig_extension:
    class: DH\DoctrineAuditBundle\Twig\Extension\TwigExtension
    arguments: ['@doctrine']
    tags:
      - { name: twig.extension }

  dh_doctrine_audit.command.clean:
    class: DH\DoctrineAuditBundle\Command\CleanAuditLogsCommand
    tags:
      - { name: 'console.command', command: 'audit:clean' }

  DH\DoctrineAuditBundle\Command\CleanAuditLogsCommand:
    alias: dh_doctrine_audit.command.clean
    public: true
