services:
  dh_doctrine_audit.configuration:
    class: DH\DoctrineAuditBundle\AuditConfiguration
    arguments: ["%dh_doctrine_audit.configuration%", "@security.token_storage", "@request_stack"]
    public: true

  dh_doctrine_audit.reader:
    class: DH\DoctrineAuditBundle\AuditReader
    arguments: ["@dh_doctrine_audit.configuration", "@doctrine.orm.default_entity_manager"]
    public: true

  dh_doctrine_audit.event_subscriber.audit:
    class: DH\DoctrineAuditBundle\EventSubscriber\AuditSubscriber
    arguments: ["@dh_doctrine_audit.configuration"]
    tags:
      - { name: doctrine.event_subscriber, connection: default }

  dh_doctrine_audit.event_subscriber.create_schema:
    class: DH\DoctrineAuditBundle\EventSubscriber\CreateSchemaListener
    arguments: ["@dh_doctrine_audit.configuration"]
    tags:
      - { name: doctrine.event_subscriber, connection: default }

  dh_doctrine_audit.twig_extension:
    class: DH\DoctrineAuditBundle\Twig\Extension\TwigExtension
    arguments: ['@doctrine']
    tags:
      -  { name: twig.extension }